/**
 * Extract region paths from map_base.svg into a TypeScript data file.
 *
 * Usage:
 *   node scripts/extract-regions.js [path-to-svg]
 *
 * If no path is given, defaults to ./public/images/map_base.svg
 * Output: src/data/map-paths.ts
 */

const fs = require("fs");
const path = require("path");

const svgPath =
  process.argv[2] ||
  path.join(__dirname, "..", "public", "images", "map_base.svg");
const outputPath = path.join(__dirname, "..", "src", "data", "map-paths.ts");

const svg = fs.readFileSync(svgPath, "utf-8");

// Extract viewBox dimensions
const vbMatch = svg.match(/viewBox="([^"]+)"/);
if (!vbMatch) {
  console.error("No viewBox found in SVG");
  process.exit(1);
}
const [, , , mapW, mapH] = vbMatch[1].split(/\s+/).map(Number);

// Extract ocean rect color
const oceanMatch = svg.match(/<rect[^>]*fill="(#[0-9a-fA-F]{6})"[^>]*\/?\s*>/);
const oceanColor = oceanMatch ? oceanMatch[1] : "#1E6EDC";

// Extract region paths (paths with data-region attribute)
const regionRegex = /<path\s[^>]*data-region="(\d+)"[^>]*\/?\s*>/g;
const dAttrRegex = /\bd="([^"]+)"/;
const regions = [];
let match;
while ((match = regionRegex.exec(svg)) !== null) {
  const regionId = match[1];
  const dMatch = match[0].match(dAttrRegex);
  if (dMatch) {
    regions.push({ id: regionId, d: dMatch[1] });
  }
}

// Extract water path (inside <g id="water">)
let waterPath = "";
const waterGroupMatch = svg.match(
  /<g\s+id="water"[^>]*>([\s\S]*?)<\/g>/
);
if (waterGroupMatch) {
  const waterDMatch = waterGroupMatch[1].match(dAttrRegex);
  if (waterDMatch) waterPath = waterDMatch[1];
}

// Extract borders path (inside <g id="borders">)
let borderPath = "";
const borderGroupMatch = svg.match(
  /<g\s+id="borders"[^>]*>([\s\S]*?)<\/g>/
);
if (borderGroupMatch) {
  const borderDMatch = borderGroupMatch[1].match(dAttrRegex);
  if (borderDMatch) borderPath = borderDMatch[1];
}

// Build TypeScript output
const lines = [
  "// Auto-generated by scripts/extract-regions.js — do not edit manually",
  "",
  `export const MAP_WIDTH = ${mapW};`,
  `export const MAP_HEIGHT = ${mapH};`,
  `export const OCEAN_COLOR = "${oceanColor}";`,
  "",
  "export interface RegionPath {",
  "  id: string;",
  "  d: string;",
  "}",
  "",
  `export const REGION_PATHS: RegionPath[] = ${JSON.stringify(regions, null, 2)};`,
  "",
  `export const WATER_PATH = ${JSON.stringify(waterPath)};`,
  "",
  `export const BORDER_PATH = ${JSON.stringify(borderPath)};`,
  "",
];

// Ensure output directory exists
const outDir = path.dirname(outputPath);
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
console.log(
  `Extracted ${regions.length} regions to ${path.relative(process.cwd(), outputPath)}`
);
console.log(`  Map size: ${mapW} × ${mapH}`);
console.log(`  Ocean color: ${oceanColor}`);
console.log(`  Water path: ${waterPath ? "yes" : "no"}`);
console.log(`  Border path: ${borderPath ? "yes" : "no"}`);
